// <auto-generated />
namespace Joker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class many_to_manyexit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(many_to_manyexit));
        
        string IMigrationMetadata.Id
        {
            get { return "201505282217215_many_to_manyexit"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
