// <auto-generated />
namespace Joker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Testing_App : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Testing_App));
        
        string IMigrationMetadata.Id
        {
            get { return "201505280407497_Testing_App"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
