// <auto-generated />
namespace Joker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class Datatype_ToString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Datatype_ToString));
        
        string IMigrationMetadata.Id
        {
            get { return "201505272335548_Datatype_ToString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
